### ISSUE TITLE
NewPipe or NewPipe Extractor?

### ISSUE THREAD

**Issue by tbm** [TeamNewPipe/documentation#21]
This is feedback from someone who discovered NewPipe about 10 minutes ago (I'm about to install it, but I haven't even used it yet).

The first page of the docs says:

> Welcome to NewPipe
>
> This site is/should be a beginner friendly tutorial and documentation for people who want to use or write services for the NewPipe Extractor

I'm confused already.  I thought the docs are about NewPipe?  What is NewPipe Extractor?

The title of the docs is "NewPipe Documentation", but really it looks like this is documentation for *developers* rather than *users*.  I think that needs to be clearer in the title (and on the web site which links to "docs": "docs" sounds like user docs).  Maybe "Developer documentation for NewPipe Extractor" or something, and have a "developers" corner on the web site where you mention GitHub and these docs.

(Hmm, you talk about Releasing a New NewPipe Version later, so maybe NewPipe Extractor isn't the best title for the docs.  But you need to be clearer on the first page and the title what these docs are about.)

**Comment by theScrabi** [comment]
It's a documentation for developers. If you want to know more about NewPipe you may want to take a look at [newpipe.net](https://newpipe.net).

**Comment by Stypox** [comment]
I was about to open an issue for the same reason. Maybe the GitHub repo description should be something like "A beginner tutorial for the NewPipeExtractor and developer guidelines for NewPipe"

**Comment by mustafavisa** [comment]
Newpipe keeps buffering!
