### ISSUE TITLE
Can not get Syntax hightlighting to work

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/documentation#5]
I can not get the Syntaxhighlighting to work with the readthedocs theme of mkdocs. @TobiGr @TheAssassin, could you please help me out here :).
According to [this](https://mkdocs.readthedocs.io/en/latest/user-guide/writing-your-docs/#fenced-code-blocks) here it should work. However every time I run `mkdocs serve` I get an error message where it tells me it could not find the hightlight.css.
```
[W 180901 21:10:20 web:2106] 404 GET /css/highlight.css (127.0.0.1) 1.27ms
```

**Comment by TheAssassin** [comment]
Sorry, I can't help with this. I'm a [Sphinx](http://www.sphinx-doc.org/en/master/) person.

**Comment by theScrabi** [comment]
You could try and learn something ;D

**Comment by TheAssassin** [comment]
Could say the same about you...

**Comment by theScrabi** [comment]
:D your right, but I'm not going to resetup the documentation.

**Comment by theScrabi** [comment]
Thx @TobiGr :)
