### ISSUE TITLE
Need help with travis

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/documentation#7]
I've been setting up a little script that checks if liks are returning 200 and are properly implemented. I wanted to make it run through travis, but it can not find the python module "requests". Could someone pls help me here?

**Comment by TheAssassin** [comment]
```
pip[3] install --user requests
sudo apt-get install python[3]-requests
sudo pip[3] install --user requests
python3 -m venv venv; . venv/bin/activate; pip install requests
[...]
```

**Comment by theScrabi** [comment]
got it fixed :) trick was to use a `requirements.txt`.
